import type { Mesh } from "../../types/mesh.types.js";
import { getTriangleNormal } from "../mesh-topology/mesh-topology.js";

const HEADER_BYTE_LENGTH = 80;
const TRIANGLE_BYTE_LENGTH = 50;

export const writeBinaryStereolithography = (mesh: Mesh): Buffer => {
  const buffer = Buffer.alloc(HEADER_BYTE_LENGTH + 4 + mesh.triangleCount * TRIANGLE_BYTE_LENGTH);
  buffer.write("Binary STL generated by scan-to-cad-pipeline", 0, "utf8");
  buffer.writeUInt32LE(mesh.triangleCount, HEADER_BYTE_LENGTH);

  let byteOffset = HEADER_BYTE_LENGTH + 4;

  for (let triangleIndex = 0; triangleIndex < mesh.triangleCount; triangleIndex += 1) {
    const normal = getTriangleNormal(mesh, triangleIndex);
    buffer.writeFloatLE(normal.x, byteOffset);
    buffer.writeFloatLE(normal.y, byteOffset + 4);
    buffer.writeFloatLE(normal.z, byteOffset + 8);
    byteOffset += 12;

    for (let cornerIndex = 0; cornerIndex < 3; cornerIndex += 1) {
      const positionOffset = mesh.indices[triangleIndex * 3 + cornerIndex] * 3;
      buffer.writeFloatLE(mesh.positions[positionOffset], byteOffset);
      buffer.writeFloatLE(mesh.positions[positionOffset + 1], byteOffset + 4);
      buffer.writeFloatLE(mesh.positions[positionOffset + 2], byteOffset + 8);
      byteOffset += 12;
    }

    buffer.writeUInt16LE(0, byteOffset);
    byteOffset += 2;
  }

  return buffer;
};
